### ISSUE TITLE
Доработка механик и адаптаций ИИ к атакам и движениям игрока

### ISSUE THREAD

**Issue by consiglieres** [BornToCodeStudio/game_UE_BornToCode#23]
Сделать "маркер" урона для бота
Прикрутить анимации
Постепенно улучшать ИИ
```[tasklist]
### Tasks
- [x] Базовая атака бота
- [ ] Исправить сенсоры бота
- [ ] Разработать другие виды атак для бота
```
