### ISSUE TITLE
Боевая система

### ISSUE THREAD

**Issue by consiglieres** [BornToCodeStudio/game_UE_BornToCode#24]
Разработать прототип Blueprint с боевой системой на персонаже и ИИ
```[tasklist]
### Tasks
- [x] Разработка атаки с рабочим уроном
- [x] Добавить уворот
- [x] Разработка сильной атаки
- [x] Разработка гаджетов/умений
- [x] Разработка блока
- [x] Разработка дальней атаки
- [x] Добавить комбо-атаки к легким ударам
- [x] Добавить фиксацию камеры на противнике
- [x] Добавить ускорение
```
